### PR TITLE
use sqlite instead of mysql

### PR DESCRIPTION
**Pull request by alexcos20**
Changes proposed in this PR:

- remove required parameters
- use sqlite
-

### CODE REVIEW

**Comment by balessan** [comment]
That change is a bad news given the time it took me to setup the MariaDB container properly in the docker-compose configuration -_-

But, definitely makes things easier, so yeah, I do approve.

**Review by ravish1729 — APPROVED** [review]
Tested, LGTM

**Comment by nandit123** [comment]
Hi @alexcos20 seems like @ravish1729 has approve this PR and others too, do you want us to merge this or you are testing it from your end?

**Comment by xlassix** [comment]
I would make the env configurable both for SQLite and the databases

**Review by nandit123 — APPROVED** [review]

**Pull request merged**
